"""viewed

Revision ID: 571bab19a0ac
Revises: beb3cc754afd
Create Date: 2019-07-26 20:53:16.784882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571bab19a0ac'
down_revision = 'beb3cc754afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('viewed', sa.PickleType(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('message', 'viewed')
    # ### end Alembic commands ###
